---
version: '3'

services:

  traefik:
    image: traefik:v1.7
    command: --web --docker --docker.watch --docker.domain=${DOMAIN} \
             --docker.exposedbydefault=false --acme.domains=${DOMAIN}
    container_name: traefik
    hostname: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik/acme.json:/acme.json
      - ${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${CONFIG}/traefik/.htpasswd:/etc/traefik/.htpasswd:ro
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:monitor.${DOMAIN}"
      traefik.port: "8080"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Sao_Paulo
    command: --schedule "0 0 6 * * *" --label-enable --cleanup
    restart: unless-stopped

  ghost:
    image: ghost
    container_name: ghost
    hostname: ghost
    user: 1000:1000
    environment:
    - url=https://www.libertai.me
    - TZ=America/Sao_Paulo
    ports:
      - 2368:2368
    volumes:
      - ./volumes/ghost/content:/var/lib/ghost/content
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:www.${DOMAIN}"
      traefik.port: "2368"
      # traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "false"
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
    - '9000:9000'
    environment:
    - TZ=America/Sao_Paulo
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/etc/localtime:/etc/localtime:ro'
    command: --no-auth --no-analytics -H unix:///var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:portainer.${DOMAIN}"
      traefik.port: "9000"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  gotify:
    image: gotify/server
    container_name: gotify
    hostname: gotify
    user: 1000:1000
    environment:
    - TZ=America/Sao_Paulo
    ports:
      - 3080:3080
    volumes:
      - ./volumes/gotify/data:/app/data
      - ./volumes/gotify/conf:/etc/gotify
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:gotify.${DOMAIN}"
      traefik.port: "3080"
      # traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
